### ISSUE TITLE
Pick a topic

### ISSUE THREAD

**Issue by zhijingjing1** [UBC-MDS/ploteasy#3]
Discuss the topic with your TA or lab instructor and proceed only after your topic has been approved by one of them.

**Comment by Julie-M-Zhu** [comment]
`
<img width="500" alt="image" src="https://user-images.githubusercontent.com/7963173/109407594-04b9d700-79bd-11eb-84ab-82170ae2f766.png">
`

**Comment by Julie-M-Zhu** [comment]
Yes，  I have talked to our TA via slack~
Hello, Hossameldin
9:13
This is Mengyuan Zhu from group 25, MDS 524～
9:13
I would like to introduce our idea on the theme of our package~
9:16
It is called PlotEasy which is oriented to those users who are not familiar with the complex param settings in ggplot or Altair, but are attempting to do simple EDAs ~
9:17
They can simply input 2 columns in a dataframe indexed by their names, and chose the aiming plotting forms(histograms, etc.)
9:17
And the function will deliver a quick plot conveniently~
Hopefully you are as excited as all us 3 members~ We do  find the interface of plotting in both R and python are not new-bee-friendly, and PlotEasy would really make Plot Easy~
