### ISSUE TITLE
Release + Submit to Canvas

### ISSUE THREAD

**Issue by zhijingjing1** [UBC-MDS/ploteasy#7]
Provide following on Canvas:

- The URL of your public project’s repo

- The URL to a release on your project repo named v0.1.0

- A link to your team work document that is accessible to the teaching team. Alternatively a copy of your team work document can be pasted there.

**Comment by Julie-M-Zhu** [comment]
Thanks, Jingjing, I have followed your instruction and submit our group work on canvas!
